// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nvidia.Clara.DicomAdapter.Database;

namespace Nvidia.Clara.DicomAdapter.Database.Migrations
{
    [DbContext(typeof(DicomAdapterContext))]
    partial class DicomAdapterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11");

            modelBuilder.Entity("Nvidia.Clara.DicomAdapter.API.ClaraApplicationEntity", b =>
                {
                    b.Property<string>("AeTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("IgnoredSopClasses")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("OverwriteSameInstance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Processor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessorSettings")
                        .HasColumnType("TEXT");

                    b.HasKey("AeTitle");

                    b.ToTable("ClaraApplicationEntities");
                });

            modelBuilder.Entity("Nvidia.Clara.DicomAdapter.API.DestinationApplicationEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("AeTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HostIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("DestinationApplicationEntities");
                });

            modelBuilder.Entity("Nvidia.Clara.DicomAdapter.API.InferenceJob", b =>
                {
                    b.Property<string>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobPayloadsStoragePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TryCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("JobId");

                    b.ToTable("InferenceJobs");
                });

            modelBuilder.Entity("Nvidia.Clara.DicomAdapter.API.Rest.InferenceRequest", b =>
                {
                    b.Property<Guid>("InferenceRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new Guid("29bb4d8c-f9c5-461f-bb72-d352c73829a0"));

                    b.Property<string>("InputMetadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputResources")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputResources")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TryCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("InferenceRequestId");

                    b.ToTable("InferenceRequests");
                });

            modelBuilder.Entity("Nvidia.Clara.DicomAdapter.API.SourceApplicationEntity", b =>
                {
                    b.Property<string>("AeTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("HostIp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AeTitle");

                    b.ToTable("SourceApplicationEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
