# Apache License, Version 2.0
# Copyright 2019-2020 NVIDIA Corporation
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
    # http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
{{- if not (.Capabilities.APIVersions.Has "dicom.clara.nvidia.com/v1beta2/InferenceRequest") -}}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: inferencerequests.dicom.clara.nvidia.com
  annotations:
    helm.sh/hook: crd-install
spec:
  group: dicom.clara.nvidia.com
  version: v1beta2
  scope: Namespaced
  names:
    plural: inferencerequests
    singular: inferencerequest
    kind: InferenceRequest

{{- end -}}