name: Publish Docs

on:
  workflow_dispatch:
    inputs:
      source_ref:
        description: 'Source Branch'     
        required: true
        default: 'release/*'
      build_num:
        description: 'Build Number'     
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.source_ref }}
    - name: Update Docs
      run: |
        export VERSION=`cat VERSION`
        export BUILD="$VERSION.${{ github.event.inputs.build_num }}"
        echo "VERSION=$VERSION, BUILD=$BUILD"
        sed -i -e "s,v0.0.0.0,v$BUILD,g" ./docs/docfx.json
        sed -i -e "s,v0.0.0.0,v$BUILD,g" ./docs/index.md
    - uses: nikeee/docfx-action@v1.0.0
      name: Build Docs
      with:
        args: docs/docfx.json
    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_site      
        publish_branch: docs
